
[phases.install]
cmds = ["yarn install"]

[phases.build]
cmds = [
  "npx prisma generate",
  "npx prisma migrate deploy || true",
  "yarn build"
]

[start]
cmd = "yarn start"

[variables]
NODE_ENV = "production"
NIXPACKS_METADATA = "nodejs,prisma,nextjs"
